### ISSUE TITLE
Add Example for notify / ERROR Message in LOGS

### ISSUE THREAD

**Issue by thundergreen** [benleb/ad-batterycheck#2]
Hi mate.. Thanks for your awesome app.. That's what I was looking for all the time without writing template automations :)

BUT Could you please do me a favour and add an example how to add / configure the notify.

```
---
batterycheck:
  module: batterycheck
  class: BatteryCheck
  notify: thorsten
```

That's my setup.

But I also get this eror at start-up:

```
2019-08-16 14:41:12.081314 INFO AppDaemon: App initialization complete
2019-08-16 14:46:06.042405 INFO AppDaemon: Reading config
2019-08-16 14:46:06.045296 INFO AppDaemon: /config/appdaemon/apps/apps.yaml added or modified
2019-08-16 14:46:06.045507 INFO AppDaemon: App 'batterycheck' changed
2019-08-16 14:46:06.046406 INFO AppDaemon: Terminating batterycheck
2019-08-16 14:46:06.046729 INFO AppDaemon: Initializing app batterycheck using class BatteryCheck from module batterycheck
2019-08-16 14:46:06.048300 INFO batterycheck: 
2019-08-16 14:46:06.048481 WARNING AppDaemon: ------------------------------------------------------------
2019-08-16 14:46:06.048699 WARNING AppDaemon: Unexpected error running initialize() for batterycheck
2019-08-16 14:46:06.048923 WARNING AppDaemon: ------------------------------------------------------------
2019-08-16 14:46:06.049390 WARNING AppDaemon: Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/appdaemon/appdaemon.py", line 1581, in init_object
    init()
  File "/config/appdaemon/apps/batterycheck/batterycheck.py", line 44, in initialize
    adutils.show_info(self.log, APP_NAME, self.cfg, list(), icon=APP_ICON)
  File "/usr/lib/python3.7/site-packages/adutils/__init__.py", line 28, in show_info
    log(app_name, ascii_encode=ascii_encode)  # type: ignore
TypeError: log() got an unexpected keyword argument 'ascii_encode'

2019-08-16 14:46:06.049558 WARNING AppDaemon: ------------------------------------------------------------

```

I also get a lot of Error like this in logs:

```
2019-08-16 15:10:40.361283 INFO batterycheck: Getting state/battery level failed for sensor.fibaro_system_fgms001_motion_sensor_temperature: get_state() got multiple values for argument 'entity_id'
```
And the Message sent is this:

```
Home-Assistant: Low Battery! {}
```

**Comment by benleb** [comment]
The app needs the current 4.0 beta (or master/dev branch) of appdaemon, sorry. I made this clear in the readme now.

**Comment by thundergreen** [comment]
Sorry but also with master branch it does not work. How would i use dev verson in hassio?

**Comment by benleb** [comment]
I dont know, i dont like hass.io... Did you upgrade to the 0.2.0 already?
